# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Resume CI - Cloudflare

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Prettify code
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{json,yaml,yml}
          only_changed: true
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - name: Generate a sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://resume.jamisonkissh.com/
          path-to-root: public
      - name: Publish to Cloudflare Pages
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: jamisonkissh-resume
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
